name : base image build for openjdk

on:
  push:
    paths:
      - dev-sec-ops/base-images/**


jobs:
  build-openjdk-24-jdk-slim-image:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: image build
        run: docker build -t ${{vars.DOCKER_REGISTRY_USER}}/openjdk-24-jdk-slim:latest -f dev-sec-ops/base-images/openjdk-24-jdk-slim  .
      
      - name: docker-hub login
        uses: docker/login-action@v2
        with:
          username: ${{vars.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PAT}}

      - name: docker push
        run: docker push  ${{vars.DOCKER_REGISTRY_USER}}/openjdk-24-jdk-slim:latest
